FROM node:22.15.0-alpine3.20

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install -y

RUN npm run db:generate

RUN cd ./apps/user-app && npm run build

CMD ["npm", "run", "start-user-app"]

