FROM node:22.15.0-alpine3.20

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json yarn.lock ./

RUN npm install -y

COPY apps/bank-webhook ./apps/bank-webhook
COPY packages ./packages

RUN npm run db:generate

RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "start-webhook-server" ]