import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@repo/ui/styles.css"
import Providers from "./providers";
import AppbarClient from "./AppbarClient";
import { auth } from "@/lib/auth";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    return (
        <html lang="en" className="">
            <body className={`${geistSans.variable} ${geistMono.variable} h-dvh`}>
                <Providers>
                    <AppbarClient user_prop={session?.user||undefined}/>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
