name: Build and Deploy on ec2 for every commit.

on: 
    pull_request: 
        branches:
          - main # Replace 'main' with your actual default branch name

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '23' # Ensure the correct version is specified
        
            - name: Install dependencies
              run: npm install

            - name: Install Sharp Manually
              run: |
                npm uninstall sharp
                npm install sharp@latest

            - name: Build Project
              run: npm run build
