name: Build and Deploy on ec2 for every commit.

on: 
    pull_request: 
        branches:
          - main # Replace 'main' with your actual default branch name

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '20' # Ensure the correct version is specified
            
            - name: Install system dependencies for sharp
              run: sudo apt-get update && sudo apt-get install -y libvips


            - name: Install dependencies
              run: npm install

            - name: Install Sharp Manually
              run: |
                npm install sharp
                export NEXT_SHARP_PATH ../../node_modules/sharp

            - name: Rebuild sharp for current OS
              run: npm rebuild sharp
            # - name: Generate Prisma Client
            #   run: npx turbo db:generate

            - name: Build Project
              run: npm run build
