name: Build and Deploy on ec2 for every commit.

on: 
    pull_request: 
        branches:
          - main # Replace 'main' with your actual default branch name

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '20' # Ensure the correct version is specified
            
            - name: Install system dependencies for sharp
              run: sudo apt-get update && sudo apt-get install -y libvips-dev


            - name: Install dependencies
              run: npm install && npm install --os=linux --cpu=x64 sharp

            - name: Clean Cache
              run: rm -rf node_modules && npm install

            - name: Rebuild sharp for current OS
              run: npm rebuild sharp

            - name: Verify sharp installation
              run: |
               node -e "console.log('nikhil')"
               node -e "console.log(require('sharp').version)"

            # - name: Generate Prisma Client
            #   run: npx turbo db:generate

            - name: Build Project
              env:
                NEXT_SHARP_PATH: ./node_modules/sharp
              run: npm run build

