name: deploy to aws

on:
    pull_request: 
        branches: 
            - main

# login
# setup buildx optional but recommended
# check build-push cmd
# build and push (file)
# verify push.

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -
                name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3
            
            -
                name: Build and Push Docker
                uses: docker/build-push-action@v6
                with:
                    context: ./docker
                    push: true
                    file: ./docker/Dockerfile.userapp
                    tags: ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_REPO_NAME}}:latest

            -
                name: Verify if push is successfull
                run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:latest
